In [64]:
import numpy as np

In [65]:
# Numpyオブジェクト情報を確認するためのユーザ関数定義:オブジェクトタイプ、構造、次元、データタイプ、オブジェクト
def np_print(arr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr))

## 算術演算

- 足し算 : +, add()
- 引き算:-, subtract()
- 割り算: /, divide()
- 掛け算:*, multiply()
- 累乗 : exp()
- 平方根:sqrt()
- ログ : log()
- 行列積: dot()

In [66]:
# 1から10未満の範囲(指定範囲)で1ずつ増加する数字をデータに持つ3*3の配列
a = np.arange(1, 10).reshape(3, 3)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [67]:
# 4から13未満の範囲で1ずつ増加する数字をデータに持つ3*3配列生成
b = np.arange(4, 13).reshape(3, 3)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
    


In [68]:
# 10~21まで3*4形態
c = np.arange(10, 22).reshape(3, 4)
np_print(c)


    type : <class 'numpy.ndarray'>  
    shape : (3, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
    


### 足し算

- 配列+配列
- np.add(arr1、arr2)

In [69]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
# 算術演算子
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [71]:
np.add(a, b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [72]:
print(a)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [73]:
# 構造が異なる配列間の算術演算時には(+)エラーが発生する.
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### 引き算

- 配列 - 配列 
- np.subtract(arr1、arr2)

In [74]:
# 算術演算子
a - b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [75]:
b - a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [76]:
# Methodの活用
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [77]:
np.subtract(b, a)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 割り算

- 配列 / 配列
- np.divide(arr1、arr2)

In [78]:
# 算術演算子
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [79]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [80]:
# Methodの活用
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [81]:
np.divide(b, a)

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

### 掛け算

- 配列*配列
- np.multiply(arr1、arr2)

In [82]:
# 算術演算子
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [83]:
b * a

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [84]:
# Methodの活用
np.multiply(a, b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### Exponent表現

- 指数(exponent) : 浮動小数点で数字を表示するときに重ね乗を使用して表現.
- (例)2.14e+2=2.14 x 102=214/2.98e-8=2.98 x 10-8=0.0000000298
- np.exp (arr) : 下 (base) が自然定数 e の指数関数に変換 (y = e**x)

In [85]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
# Exponent関数
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 平方根

- np.sqrt(arr)

<img src='img_2/sqrt.gif' width='400' height='200' align='left'>

In [87]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 行列積

- np.dot(a, b)

<img src='img_2/dotProduct.png' width='400' height='200' align='left'>

In [88]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [89]:
np.dot(a, b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [90]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Numpy配列の演算

#### 2. 比較の演算

1) 要素
    - 値に対する比較 : =, !=
    - 大きさに対する比較 : >, <, >=, <=

2) 配列
    - 二つの配列の全体に対する比較 : array_equal (a, b)

In [91]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [92]:
# 二配列要素について値が等しいかを比較
# 返却 : 各要素ごとの比較の結果(T/F)が配列で表現される
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [93]:
np_print(a == b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : bool
    data :
 [[False False False]
 [False False False]
 [False False False]]
    


In [94]:
#二つの配列の要素について値が違うのかを比較
a != b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [95]:
# 二つの配列の要素について大きさの比較
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
# 二つの配列が完全に一致するかどうかを照会
# 二つの配列の中で一つの要素でも違えばFalse
# 一つのT/Fで返還
np.array_equal(a, b)

False

### Numpy配列演算
3.集計関数

- Numpy配列に対して集計関数を適用するときは必ずaxisに設定された基準に従って演算遂行
- 別途に値を指定しなければデフォルト値は axis = None に指定
    - axis
    - axis = None <br>
        全体データを一つの配列と見なし、集計関数の演算範囲を全体配列に指定
        <br>
        <img src='img_2/axis_None.jpg'width='150'height='150'align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        -axis=0<br>
        列を基準に同一の列にある要素を一つのグループでまとめて集計関数の演算範囲に指定
        <br>
        <img src='img_2/axis_0.jpg'width='150'height='150'align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        -axis=1<br>
        行を基準に同一の行にある要素を一つのグループでまとめて集計関数の演算範囲に指定
        <br>
        <img src='img_2/axis_1.jpg'width='150'height='150'align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

    - 集計関数 : 配列オブジェクトに対するメソッドとして使用するかNumpyライブラリのメソッドとして使用する二つの方法
        - 合計 : sum()
        - 最小値 : min()
        - 最大値: max()
        - 累積合計 : cumsum()
        - 平均 : mean()
        - 中央値: median()
            - 大きさ順に並べたデータに対して中央に位置する値
        - 相関係数 : corrcoef()
            -データ間の相関関係を示す数値(-1<=r<=1)
        - 標準偏差:std()
            - 分散の平方根,データが平均から散らばっている程度
            - 分散 = 偏差(要素-全体平均)二乗の平均
        - 原油高: unique()

In [97]:
# 使用する配列オブジェクトの確認
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [98]:
# 合計 - 全体基準 => 全ての要素に対する合計
# 1) 配列タイプの・メソッド:arr.sum()
# 2) numpy関数:np.sum(arr)
a.sum()

45

In [99]:
np.sum(a)

45

In [100]:
# 合計 - row、横軸基準
# Method、np関数のパラメータ値:axis=1
# 結果:[最初の行の合計、二番目の行の合計、三番目の行の合計...]
print(c.sum(axis=1))
print(c)

[46 62 78]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [101]:
# 合計 - column、縦軸基準
# Method, np関数のパラメータ値:axis=0
# 結果値:[一列目の和、二列目の和、三列目の合計]
c.sum(axis=0)

array([42, 45, 48, 51])

In [102]:
#最小値 - 全体基準
#1)配列タイプのMethod:arr.min()
#2)numpy関数:np.min(arr)
c.min()
np.min(c)

10

In [103]:
# (参考) Pythonリストで最小値を探す
x = [1, 2, 3, 4]
min(x)

1

In [104]:
# 最小値 : 各横軸ごとに最小値を探す(axis=1)
# 結果値 : [最初の列の最小値、次の列の最小値 ...]
print(c.min(axis=1))
print(c)
np.min(c, axis=1)

[10 14 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


array([10, 14, 18])

In [105]:
# 最小値-各縦の最小値を探す(axis=0)
# 結果値:[一番目の最小値、二番目の行の最小値...]
c.min(axis=0)
np.min(c, axis=0)

array([10, 11, 12, 13])

In [106]:
# 最大値 - 全体基準
# 1) 配列タイプのMethod:arr.max()
# 2) numpy関数:np.max(arr)
c.max()
np.max(c)

21

In [107]:
# 最大値 - 横基準(axis=1)
c.max(axis=1)
np.max(c, axis=1)

array([13, 17, 21])

In [108]:
# 最大値 - 縦基準(axis=0)
c.max(axis=0)
np.max(c, axis=0)

array([18, 19, 20, 21])

In [109]:
# 累積合計 - 全体基準
# 1) 配列タイプのMethod:c.cumsum()
# 2) numpy関数np.cumsum()
# 結果値:
c.sum()

186

In [110]:
c.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165, 186],
      dtype=int32)

In [111]:
#累積合計 -横基準
c.cumsum(axis=1)
np.cumsum(c, axis=1)

array([[10, 21, 33, 46],
       [14, 29, 45, 62],
       [18, 37, 57, 78]], dtype=int32)

In [112]:
# 累積合計 - 縦基準
c.cumsum(axis=0)
np.cumsum(c, axis=0)

array([[10, 11, 12, 13],
       [24, 26, 28, 30],
       [42, 45, 48, 51]], dtype=int32)

In [113]:
# 平均-全体基準
# 1) 配列タイプのMethod:arr.mean()
# 2) numpy関数:np.mean(arr)
c.mean()
np.mean(c)

15.5

In [114]:
# 平均 - 横基準
c.mean(axis=1)
np.mean(c, axis=1)

array([11.5, 15.5, 19.5])

In [115]:
# 平均 - 縦基準
c.mean(axis=0)
np.mean(c, axis=0)

array([14., 15., 16., 17.])

In [116]:
# 中央値 -全体基準
#  numpy関数: np.median()
# a.median()は存在しない。
np.median(c)

15.5

In [117]:
#中央値 - 横基準
np.median(a, axis=1)

array([2., 5., 8.])

In [118]:
#中央値 - 縦基準
np.median(a, axis=0)

array([4., 5., 6.])

In [119]:
# 相関係数 : 二つのデータ間の相関関係
# numpy関数:np.corrcoef(arr1、arr2)
x = np.array([15, 12, 27, 37 ,29])
y = np.array([1, 4, 2, 9, 7])

In [120]:
# 自分自身を対象にした相関関係
np.corrcoef(x, x)

array([[1., 1.],
       [1., 1.]])

In [121]:
# 他の配列2個を活用した相関係数matrix
# 結果 : 対称型マトリックス(対角線を境界に上位,下位三角形のいずれか一つだけ解釈してもよい。)
# 右、下に向ける対角線は自分自身との相関関係(いつも1)
np.corrcoef(x, y)

array([[1.        , 0.72615657],
       [0.72615657, 1.        ]])

In [122]:
# Numpyでは3つの要素を利用した相関度を求めることが不可能だ。
# Pandasなどを利用すれば、3つ以上の配列も相関度を求めることができる。
# ただし、この場合は2つずつ組み合わせることができる場合の数を計算して相関度をチェックできる。
z = np.array([0.3, 0.5, 0.6, 0.8, 1.3])

In [123]:
np.corrcoef(x, y, z) # numpyでは3つの要素を利用した相関も求めることができない。エラー発生!

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [124]:
#標準偏差 - 全体基準
# 1) 配列タイプのMethod:arr.std()
# 2) numpy関数:np.std(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
a.std()

2.581988897471611

### (参考)データが広がっている程度を表す概念

- 1.偏差(std/sd):単位に対する補正が入っていないので、相対的な比較が困難.

- 2.変動係数(cv):偏差/平均
    - 二つ以上の変数(互いに異なる単位を使用する場合)についてデータが広がっている程度を把握する場合

In [126]:
# 標準偏差 - 横基準
a.std(axis=1)
np.std(a, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [127]:
# 標準偏差 - 縦基準
a.std(axis=0)
np.std(a, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [128]:
# 原油高 -全体値に適用
# numpy 함수 : np.unique(arr)
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
# 0以上3未満の整数値を持つ3*3列配列生成
g = np.random.randint(0, 4, (3, 3))
np_print(g)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[3 0 3]
 [0 2 2]
 [2 0 2]]
    


In [130]:
np.unique(g)

array([0, 2, 3])

In [131]:
# 原油高 -横基準
# 一つの街路に対して構成要素の組合せが固有の街路に返還
np.unique(g, axis=1)

array([[0, 3, 3],
       [2, 0, 2],
       [0, 2, 2]])

In [132]:
# 原油高 -縦基準
# 結果値:固有の縦の組み合わせの配列の返却
np.unique(g, axis=0)

array([[0, 2, 2],
       [2, 0, 2],
       [3, 0, 3]])

### BroadCasting

- 異なる構造(shape)を持つ配列に対して演算を行う時構造を合わせる過程
- 配列とスカラ値間の演算
- 配列と配列の間の演算
- BroadCasting規則:軸の長さが一致するか、二つの一つの長さが1人、二つの配列について互換性を持つ。
<img src='img/broadcast.png' width='600' height='400' align='left'>

In [133]:
# 使用する配列オブジェクトの確認
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
    


In [134]:
a + b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

#### 1.配列と値(single value、scala)

- スカラー値を配列の構造と同一の配列に変形して演算遂行

In [135]:
# 構造が異なる配列間の演算
# a配列のすべての要素にそれぞれ10ずつたす
a + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [136]:
# スカラー -> 配列変形
# aの配列の形3*3の構造にすべての要素が10人配列生成。
scalar_arr = np.full_like(a, 10)
np_print(scalar_arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
    


In [137]:
a + scalar_arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### 2.お互いに異なる構造の配列

- 行、列の最大長さを基準に構造を生成した配列に変形して演算遂行
- 拡張された行、列に対して既存の配列と同一のデータで構成

In [138]:
# 1*4の構造で1、2、3、4を値とする配列x生成
# 4*1の構造で1、2、3、4を値とする配列y生成
x = np.arange(1, 5).reshape(1, 4)
y = np.arange(1, 5).reshape(4, 1)

np_print(x)
np_print(y)


    type : <class 'numpy.ndarray'>  
    shape : (1, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3 4]]
    

    type : <class 'numpy.ndarray'>  
    shape : (4, 1)  
    dimension : 2  
    dtype : int32
    data :
 [[1]
 [2]
 [3]
 [4]]
    


In [139]:
# 配列xを同じ値に4行に拡張した新しい配列生成
# 行きの方向に配列追加(縦の長さ増加)Method:np.append(arr1、arr2、axis=0)
new_x = np.append(x, x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [140]:
new_x = np.append(new_x, new_x, axis=0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [141]:
# 配列yを同じ値に4列に拡張した新しい配列生成
# 列の方向に(横方向に)配列の追加Method:np.append(arr1、arr2、axis=1)
new_y = np.append(y, y, axis=1)
new_y

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [142]:
new_y = np.append(new_y, new_y, axis=1)
new_y

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [143]:
# 1*4の配列や4*1の配列のBroadcasting演算
print(x)
print(y)
print(x + y)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [144]:
# 4*4と同一の構造の配列間の演算
new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### Vector演算

- 要素に対する演算をVector演算で処理すれば一般的なforの繰り返しで演算作業を処理することより遥かに優れた処理速度で効率的な作業が可能

In [145]:
# 0から始まり、10000000個の要素を持った配列生成
x = np.arange(10000000)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [148]:
%%time
# 当該セルの動作の完了所要時間を知らせるIPythonコマンド。
# セルのいちばん上に位置(注釈もあればならない)

# 繰り返しを通じた合計
# 時間単位:1s=1,000ms(ミリ秒)=1,000,000µs(マイクロセカンド)
loop_result = 0
for i in x :
    loop_result += i
loop_result

C:\Users\dltjs\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in long_scalars
  


Wall time: 4.28 s


-2014260032

In [149]:
%%time
# Vector演算による合計演算
np.sum(x)

Wall time: 7.98 ms


-2014260032