# Numpy

- Numeriacal Python

- Python Machine Running Package scikit-learnで基本データ構造として使用され、Numpy配列形態のデータを使用する.

- Pythonベースのデータ分析環境において、行列およびVector演算に必要な様々な関数を提供する.

- メモリー消耗の多い繰り返しなしに全体データ配列に速い演算を処理できる標準数学関数.

- 配列 : 同じ特性(データタイプ)および一定のルールを持つ複数の要素が並んでいるデータ集合.

- Python listオブジェクトを使用する際、よりNumpyのndarrayオブジェクトを使用すれば、演算速度が改善され、より多くのデータをもっと速く処理することができる.

In [1]:
#ライブラリインポート : Numpy
#asというニックネームを宣言した後は、ニックネームで該当ライブラリの機能を使うことができる.
import numpy 
import numpy as np 

In [2]:
#ライブラリVersionを確認
np.__version__

'1.16.4'

## Numpy配列 : numpy.ndarray

- 多次元配列(1次元、2次元、3次元)で立体的なデータ構造を構成して複数のデータ方向性を持っている.

- 配列属性 : shape, ndim, dtype など

- データ方向:axis=0(行/高さ)、1(列/幅)、2(チャンネル/深さ)

- 写真を入れるときはimg tagを使います。



<img src='img/nparr1.jpg' width='600' height='400' align='left'>

### 1.配列生成

- np.array(data)

- Python listオブジェクトを受け取ってnumpy listに交換してくれるコマンド

- 配列属性
    - shape:構造(行、列、次元)
    - ndim: 次元
    - dtype: データタイプ
    - size: 要素個数 = 行 * 列 *次元

- 配列Method
    - astype():データタイプ変換(文字を数字でとか...)

- Python内蔵関数を使った属性値
    - type() : オブジェクトの資料型確認
    - len():要素内部の資料の長さ

- Numpy関数を使った属性
    -reshape(row、column):配列の再配置(1*12を3*4の形に変えたり...)

- kind:データ種類に対する区分記号
    - b: boolean
    - i : 整数(int)
    -:符号のない整数(unsigned int, +-概念がなく、絶対値だけが存在する。)
    - f : 間違い
    - c: 複素浮動小数点
    - O:オブジェクト
    - S:バイト文字列(asciiコード,英文字,一部特文,数字)
    - U:ユニコード文字列(韓国語,日本語,中国語,タイ語,アラビア語など英語ではない文字)

In [3]:
#.Python 1次元のリストをNumpyに交換.
tmp = [1,2,3,4,5,6]
arr = np.array(tmp)
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
# 配列オブジェクトの属性 - タイプ(資料型)
print(type(arr), type(tmp))

<class 'numpy.ndarray'> <class 'list'>


In [5]:
# 配列オブジェクトの属性 - 構造確認:shape(横)、列(縦)、次元(面)
# (定数, ) : 定数の個数のアイテムを持つリストが配列に変換された結果物
arr.shape

(6,)

In [6]:
# 配列オブジェクトの属性-長さ=>(n、)[1D array]:アイテムの個数
len(arr)

6

In [7]:
# 配列オブジェクトの属性 -次元
arr.ndim

1

In [14]:
# 配列要素の属性 -要素の数
arr.size

6

In [8]:
# 配列オブジェクトの属性 - データタイプ
arr.dtype

dtype('int32')

In [10]:
# 配列オブジェクトの属性 - データタイプ変換 : astype => 原本データ保持
arr2 = arr.astype(float)

In [11]:
print(arr.dtype, arr2.dtype)

int32 float64


In [12]:
# 配列構造変換
# 基本配列の要素の数と変換しようとする構造の数は同じでなければならない。
arr.reshape(2,3) # (2*3が6なので)可能、reshape(縦の長さ、横の長さ)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Numpyオブジェクト情報をより楽に確認するためのユーザ関数定義
# オブジェクトタイプ、構造、次元、データタイプ、内部資料を確認するために定義する関数
def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [14]:
# リスト要素タイプが一貫していないと、優先順位によって全体dtypeが統一される.
# 優先順位:str(一番高い) > float > int(一番低い)
# 他のタイプの混合1:int+str=str
tmp = [1,2,3,"4"]
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : <U11
    array data : 
 ['1' '2' '3' '4']


In [16]:
# 他のタイプ混合2 : int+float=float
tmp = [1,2,3.3,4]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : float64
    array data : 
 [1.  2.  3.3 4. ]


In [17]:
# 他のタイプ混合3 : float + str = str
tmp = ['1',1.2,0.3]
arr1 = np.array(tmp)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (3,)
    ndim : 1
    dtype : <U3
    array data : 
 ['1' '1.2' '0.3']


In [20]:
# Python 2次元リストでNumpy配列生成
# 2次元配列のshape属性は(行(縦の長さ)、列(横の長さ)だけ返還。
tmp = [[1,2,3,4],[5,6,7,8]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]
 [5 6 7 8]]


In [21]:
# Python 3次元リストでnumpy配列生成
tmp = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr = np.array(tmp)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 2, 3)
    ndim : 3
    dtype : int32
    array data : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
# データファイルをparameterに指定してNumpy配列タイプの属性を変えることができる.
# np.array(data, dtype="資料型")
tmp = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr = np.array(tmp, dtype=float)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 2, 3)
    ndim : 3
    dtype : float64
    array data : 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


### 生成および初期化

- 1.初期値を指定してデータを自動的に持つ配列を生成

    - np.zeros()
    - np.ones()
    - np.full()
    - np.eye()
    - np.empty()

#### 1-1.np.zeros(shape(形)、dtype=float)

- 指定された構造の配列を生成し、すべての要素を0に初期化(zeros)
- shape: tuple形式で行、列を指定
- dtype:配列で使用するデータタイプを指定,基本はnumpy.float64

In [24]:
# dtypeを指定していない基本(float)で生成.
#3*4構造の中にすべての値を0とする.
#2次元から構造はTupleにしなければならない.
arr = np.zeros((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# dtypeをintに変えて生成
arr = np.zeros((3,4), dtype=int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 1-2.np.ones(shape(行、列)、dtype=float)
- 指定された構造の配列を生成し、すべての要素を1に(ones)初期化.
- shape: tuple資料で行と列の構造を指定.
- dtype:配列のデータタイプを指定,基本 = numpy.float64

In [26]:
#3*4構造のなかで、初期化の値をすべて1に持つ配列.
arr = np.ones((3, 4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 1-3.np.full(shape、fill_value、dtype=float)
- 指定された構造の配列を生成し、全ての要素をfill_value値で初期化
- shape: tuple 資料型で行と列の構造を指定
- dtype = 配列のデータタイプを指定,デフォルト値 = numpy.float64

In [28]:
# 3*4列構造のなかで、初期化価を全て5に持つ配列
arr = np.full((3, 4),5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


#### 1-4.np.eye(N、M=None、dtype=float)
- N,M)構造の単位行列を生成
- M:十数を指定、基本=N
- dtype:配列のデータタイプを指定,基本 = numpy.float64

In [38]:
# 3*3の単位行列
# 縦と横の長さが同じindexに1にして、残りは0だ.
arr = np.eye(3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
arr = np.eye(5,3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
