In [2]:
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 配列整列

- sort(axis=-1):axisを基準に要素を昇順整列
    - デフォルト値(axis=-1):現在、配列の最後のaxis
    - axis=0:列の単位整列
    - axis=1:行の単位整列
    - 原本オブジェクトに整列結果が反映される,

- np.sort(axis=-1):axisを基準に要素を昇順整列
    - デフォルト値(axis=-1):現在、配列の最後のaxis
    - axis=0:列の単位整列
    - axis=1:行の単位整列
    - 整列した新しい配列を返還する.

- np.argsort(arr) : 整列順序を返還
    - デフォルト値(axis=-1):現在、配列の最後のaxis
    - axis=0:列の単位整列
    - axis=1:行の単位整列

In [3]:
# 1次元配列の生成
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [4]:
x[::-1]

array([4, 3, 2, 1, 0])

In [5]:
a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [4 4 8 9 7]
    


In [6]:
# 1.np.sort(資料)->の原本自体が変わっていない。
np.sort(a)

array([4, 4, 7, 8, 9])

In [7]:
a

array([4, 4, 8, 9, 7])

In [8]:
# 2.資料。sort()->原本資料に反映される。
a.sort()
print(a)

[4 4 7 8 9]


In [9]:
b = np.random.randint(0, 10, 5)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [2 4 6 5 1]
    


In [10]:
# np.argsort(資料)は資料内部のアイテムを順番に並べ替えるために
# 現在indexのいくつかの資料をどのような順番に配置すべきかを見せてくれる。
np.argsort(b)

array([4, 0, 1, 3, 2], dtype=int64)

In [11]:
# 0以上1未満の範囲で無作為に値を持つ3*3の配列2つの生成
a = np.random.random((3, 3))
b = np.random.random((3, 3))
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.87006434 0.55084083 0.04841083]
 [0.30119923 0.90668097 0.16113353]
 [0.87638447 0.27829401 0.48439279]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.22902173 0.10508067 0.04055682]
 [0.52396576 0.19831146 0.04957306]
 [0.13964476 0.79111165 0.19935047]]
    


##### 例)2次元配列の場合

- 基本axis=-1
- 現在、配列のaxis=0、1
- 最後のaxis=1(行基準整列)

<img src='img_2/sortaxis1.jpg' width='200' height='200' align='left'>

In [12]:
# 基本方向 (axis=-1)
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.87006434 0.55084083 0.04841083]
 [0.30119923 0.90668097 0.16113353]
 [0.87638447 0.27829401 0.48439279]]
    


array([[0.04841083, 0.55084083, 0.87006434],
       [0.16113353, 0.30119923, 0.90668097],
       [0.27829401, 0.48439279, 0.87638447]])

##### axis=0(列基準整列)

<img src='img_2/sortaxis0.jpg' width='200' height='200' align='left'>

In [13]:
# 縦の方向の基準を整列
np_print(a)

np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.87006434 0.55084083 0.04841083]
 [0.30119923 0.90668097 0.16113353]
 [0.87638447 0.27829401 0.48439279]]
    


array([[0.30119923, 0.27829401, 0.04841083],
       [0.87006434, 0.55084083, 0.16113353],
       [0.87638447, 0.90668097, 0.48439279]])

## Indexing ,Slicing

### 1.Indexing:一つの要素について参照
- 各次元によって配列が参照するIndexの数が異なる。
    - 1次元配列:Index 1つ
    - 2次元配列:Index 2つ
    - 3次元配列:Index 3つ

- Indexingで参照した要素について修正可能

- Index配列を伝え、複数の要素を参照

In [14]:
# 0から23までの1ずつ増加する値をアイテムとする1次元配列生成
arr1= np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [15]:
# 1次元配列Indexing:1度index要素のアクセス
arr1[1]

1

In [16]:
# 1次元配列Indexing:最後のindex要素のアクセス
arr1[-1]

23

In [17]:
# 1次元配列Indexingを通じた値の修正
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [18]:
# 配列arr1を利用して4*6形態の2次元配列を生成
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [19]:
# 2次元配列Indexing:2次元配列[行のindex、(列のindex)]
# 一つの行にアクセス:1行
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [20]:
# 一つの列にアクセス:すべての列について一つの行に接近
# 返り値:1d array
arr2[:, 0]

array([ 0,  6, 12, 18])

In [21]:
# 一つの値に接近
# 3 * 3
arr2[2, 2]

14

In [22]:
# 複数の横の値を照会
# 二重的なリスト利用
arr2[[0, 3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [23]:
# 複数の縦の値を照会
# 二重的なリスト利用
arr2[:, [0, 2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [24]:
# 2次元配列インデクシンを通じた値を修正
# 一つの行/列に対してすべて同一の値に修正 : 伝達する値をスカラ値で伝達
# 異なる値に修正 :配列要素個数に合わせて配信
# 一つの値を修正する例示
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [25]:
# 複数の値に修正
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [26]:
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  9   9   9  99  99  99]
 [  9   9   9   9   9   9]
 [ 18  19  20  21  22 100]]
    


In [27]:
# 3次元配列生成
# 構造:2つの層、4*3
# np.arange()=>24個のサイズ
arr3 = np.arange(0, 24).reshape((2, 4, 3))
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (2, 4, 3)  
    dimension : 3  
    dtype : int32
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [28]:
# 3次元配列Indexing:arr[層、行、列]
# 0番目のページに接近
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
arr3[0, 1]

array([3, 4, 5])

In [30]:
arr3[0, 1, 0]

3

In [31]:
# 3次元配列も配列Indexingで価格の修正が可能である
# スカラー演算を通した同じ値に修正
arr3[1] = 0
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [32]:
# 一つのページについてお互いに異なる値に修正:要素の値を同じ構造、個数で配信
arr3[1, 1] = [1, 2, 3]
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [33]:
arr3[0] = [[10, 20, 30],
          [40, 50, 60],
          [0, 0, 0],
          [0, 0, 0]]

In [34]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [35]:
#インデックス配列を伝え、いくつかの要素を参照
arr3[0, 0, 0] #10
arr3[0, 1, 1] #50
arr3[0, 2, 2] # 0

0

In [36]:
#複数のindexingを配列で配信
arr3[0, [[0, 1, 2], [0, 1, 2]]]

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]]])

In [37]:
# 内部要素indexingをする時、一般的なリストを使用する場合
# 列単位で持ってくるのではなく、内部要素の一つ一つ単位で持ってくる。
arr3[0, [0, 1, 2], [0, 1, 2]]

array([10, 50,  0])

### 2.Slicing:複数の要素について参照
-axisごとに範囲指定
    - from_index:スタートindex(含む)、0の場合省略可能
    - to_index:終了index(未含む)、最後のindexの場合省略可能
    - step:連続しない範囲の場合間隔を指定
- 列だけを照会する場合: 全体行にslicingでアクセス後に特定の列を照会

In [38]:
# 0から23までの1ずつ増加する定数の値を持つ1次元配列生成
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [39]:
# 1次元配列slicing:1度indexから4度indexまで接近
a[1:5]

array([1, 2, 3, 4])

In [40]:
# 1番目indexから4番目indexまで2つずつ飛ばして接近
a[1:5:2]

array([1, 3])

In [41]:
# 2次元配列生成
b = a.reshape(6, 4)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (6, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [42]:
# 2次元配列slicing:1行から4行まで接近
# 2d_array[行(:列:間隔)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
#1行から4行に対して2列から4列まで接近
b[0:4, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [44]:
# 2次元配列slicingを通じた値を修正
# 1行目から4行きに対して2列から4列までの部分配列について
# 最初の行と最後の列を除いたすべての値を99に修正
s_arr = b[0:4, 1:]
s_arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [45]:
s_arr[1:, :2] = 99

In [46]:
# 原本の配列が変更されたかどうか確認
s_arr

array([[ 1,  2,  3],
       [99, 99,  7],
       [99, 99, 11],
       [99, 99, 15]])

In [47]:
# 2次元配列slicing:不連続な範囲の熱に対するindexing
# step1.全体の行に対してアクセス
# step2.複数の列のindexcing配列配信
# bの全体の行+1、3番目の列
# b[行、列]
b[:, [1, 3]]

array([[ 1,  3],
       [99,  7],
       [99, 11],
       [99, 15],
       [17, 19],
       [21, 23]])

### 練習問題

- 下記の情報は学生の学番、英語の成績、国語の成績、数学の成績情報です。
- 当該情報を最初の行(row)に、学籍番号、二番目の行に英語の成績、三番目の行に国語の成績、四番目の行に数学の成績を保存した配列で作って学生別に英語の成績を昇順基づき、各列(column)を整列してください。

<img src='img_2/sort_q1.png' align='left'>

In [48]:
data = [[1,2,3,4],
        [70, 97, 45, 56],
        [87, 84, 33, 67],
        [46, 80, 75, 78]]
arr = np.array(data)

In [49]:
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (4, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4]
 [70 97 45 56]
 [87 84 33 67]
 [46 80 75 78]]
    


In [50]:
# 英語の成績を基準に上向き整列
np.sort(arr)   # 各行に対して個別に昇順整列が適用される。

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [33, 67, 84, 87],
       [46, 75, 78, 80]])

In [51]:
arr

array([[ 1,  2,  3,  4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]])

In [52]:
# 英語の成績を基準に上向き順の整列順位
i = np.argsort(arr[1])
i

array([2, 3, 0, 1], dtype=int64)

In [53]:
arr[0] = arr[0][i]
arr[1] = arr[1][i]
arr[2] = arr[2][i]
arr[3] = arr[3][i]
#arr[0, [i]]

In [54]:
arr

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

## 条件索引(Boolean Indexing)

- 配列の要素に対して条件を適用してTrue, Falseで条件に対する結果返還
- Trueに該当する要素だけを照会して条件を満たす結果返還

In [55]:
# 2次元配列生成
b

array([[ 0,  1,  2,  3],
       [ 4, 99, 99,  7],
       [ 8, 99, 99, 11],
       [12, 99, 99, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
# スカラ演算を通じた10より大きな要素の調査
b > 10

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
# 条件色である方法
# 資料[資料を含む条件式]
b[b>10]
b[b>10].size

17

In [58]:
# 条件索引を利用して偶数の資料だけを残してみてください。
# 条件索引の場合、様々な条件をかけたい時は各条件一つ一つを()で包んでくれて
# 条件の間をandの場合は&を、orの場合は|につなげる
b[(b%2 == 0) & (b != 0)]

array([ 2,  4,  8, 12, 16, 18, 20, 22])

### 練習問題

条件索引を活用して公務員の試験の合格者の平均を求めてください。
合格の点数は60点以上です。

下記は試験の点数結果です。<br>
[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
55, 56, 51]

In [59]:
score = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

In [60]:
score[score>=60].mean()

77.33333333333333

## 配列コピー

- indexing、slicingを通じて返還された配列は原本配列に対して独立した新しいオブジェクトではなく原本配列と従属的なオブジェクト
- 原本と独立した複写された配列を生成 : arr.copy() / np.copy(arr)

In [61]:
a = [1, 2, 3]
a2 = [1, 2, 3]

In [62]:
# 浅いコピー
b = a
b

[1, 2, 3]

In [63]:
# 深いコピー1:=を使用して、インデクシンを指定してコピーすれば永久的な複写する。
c = a2[:]
c

[1, 2, 3]

In [64]:
b[0] = 10
c[0] = 10

In [65]:
print(a, a2, b, c)

[10, 2, 3] [1, 2, 3] [10, 2, 3] [10, 2, 3]


In [66]:
arr1 = np.arange(0, 4).reshape(2, 2)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (2, 2)  
    dimension : 2  
    dtype : int32
    data :
 [[0 1]
 [2 3]]
    


In [67]:
# 深いコピー2
arr2 = arr1.copy()

In [68]:
# 浅いコピー
arr3 = arr1

In [69]:
arr2[0, 0] = 100

In [70]:
arr1

array([[0, 1],
       [2, 3]])

In [71]:
arr2

array([[100,   1],
       [  2,   3]])

In [72]:
arr3[0, 0] = 100

In [73]:
arr3

array([[100,   1],
       [  2,   3]])

In [74]:
arr1

array([[100,   1],
       [  2,   3]])